project:
  type: book
  output-dir: docs

book:
  title: "r"
  author: "Pawan"
  date: "11/03/2025"
  chapters:
    - index.qmd
    - getting-start-with-R.md
    - 01-intro-to-r.Rmd
    - 02-starting-with-data.Rmd
    - data-frame.Rmd
    - data-types.Rmd
    - 03-dplyr.Rmd
    - 04-tidyr.Rmd
    - 05-ggplot2.Rmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



